export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  journal: "/journal",
  journalNew: "/journal/new",
  journalDetails: (id: string) => `/journal/${id}`,
  buddy: "/buddy",
  buddyHistory: "/buddy/history",
  emotionInsights: "/insights/emotion",
  profileSettings: "/settings/profile",
  notificationSettings: "/settings/notifications",
  privacySettings: "/settings/privacy",
  trustedContacts: "/settings/trusted-contacts",
  exportData: "/settings/export",
  crisisHelp: "/crisis-help",
} as const;
