server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files  / /index.html;
    }

    location /api/ {
        proxy_pass http://backend:4000;
        proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
        proxy_set_header X-Real-IP ;
        proxy_set_header Authorization ;
    }

    location /_next/ {
        alias /usr/share/nginx/html/_next/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
