import { createCipheriv, randomBytes } from "node:crypto";
import type { OwnedDatabase } from "@echo/service-core";
import { ServiceError } from "@echo/service-core";
const bytea = (value: Buffer) => `\\x${value.toString("hex")}`;
export function phq8(answers: number[]) { const score = answers.reduce((sum, value) => sum + value, 0); const severity = score <= 4 ? "minimal" : score <= 9 ? "mild" : score <= 14 ? "moderate" : score <= 19 ? "moderately_severe" : "severe"; return { score, severity, disclaimer: "This screening result is not a diagnosis. Contact a qualified professional for clinical advice." }; }
export class AssessmentService {
  constructor(private database: OwnedDatabase, private key: Buffer, private keyVersion: number) { if (key.length !== 32) throw new Error("JOURNAL_ENCRYPTION_KEY_BASE64 must decode to 32 bytes."); }
  async recordMood(userId: string, input: { moodScore: number; energyScore?: number; anxietyScore?: number; note?: string }) { let protectedNote = {}; if (input.note) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", this.key, iv); const encrypted = Buffer.concat([cipher.update(input.note, "utf8"), cipher.final()]); protectedNote = { note: null, note_ciphertext: bytea(encrypted), encryption_iv: bytea(iv), encryption_auth_tag: bytea(cipher.getAuthTag()), encryption_key_version: this.keyVersion }; } const { data, error } = await this.database.from("mood_entries").insert({ user_id: userId, mood_score: input.moodScore, energy_score: input.energyScore, anxiety_score: input.anxietyScore, ...protectedNote }).select("id, mood_score, energy_score, anxiety_score, recorded_at, created_at").single(); if (error || !data) throw new ServiceError(503, "DATABASE_UNAVAILABLE", "The mood entry could not be saved."); return data; }
  async listMoods(userId: string) { const { data, error } = await this.database.from("mood_entries").select("id, mood_score, energy_score, anxiety_score, recorded_at, created_at").eq("user_id", userId).order("recorded_at", { ascending: false }).limit(90); if (error) throw new ServiceError(503, "DATABASE_UNAVAILABLE", "Mood entries could not be loaded."); return data ?? []; }
}
