# generated by datamodel-codegen:
#   filename:  analysis-request.schema.json

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class AnalysisRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request_id: UUID
    journal_text: str = Field(..., max_length=20000, min_length=1)
    language: str = Field(..., max_length=16, min_length=2)
