# generated by datamodel-codegen:
#   filename:  analysis-response.schema.json

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Severity(Enum):
    minimal = 'minimal'
    mild = 'mild'
    moderate = 'moderate'
    moderately_severe = 'moderately_severe'
    severe = 'severe'


class AnalysisResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request_id: UUID
    phq8_score: int = Field(..., ge=0, le=24)
    severity: Severity
    urgent_language_detected: bool
    model_version: str = Field(..., min_length=1)
    processing_time_ms: int = Field(..., ge=0)
