-- Contact listings checked against official sources on 2026-09-12.
-- This verifies publication, not live call delivery. Do not reset other reviewed resources.
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','NCMH','NCMH Crisis Hotline','1553','24-hour crisis support; network access may vary.','https://ncmh.gov.ph/','https://quezoncity.gov.ph/national-suicide-prevention-week-4/',true,true,'2026-09-12T00:00:00Z',1
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='NCMH Crisis Hotline' and phone_number='1553');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','NCMH','NCMH mobile (Smart)','+639190571553','Crisis support; network charges may apply.','https://ncmh.gov.ph/','https://quezoncity.gov.ph/national-suicide-prevention-week-4/',true,true,'2026-09-12T00:00:00Z',2
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='NCMH mobile (Smart)' and phone_number='+639190571553');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','NCMH','NCMH mobile (Globe)','+639178998727','24-hour crisis support; network charges may apply.','https://ncmh.gov.ph/','https://quezoncity.gov.ph/national-suicide-prevention-week-4/',true,true,'2026-09-12T00:00:00Z',3
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='NCMH mobile (Globe)' and phone_number='+639178998727');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','NCMH','NCMH mobile (Globe/TM)','+639663514518','Crisis support; network charges may apply.','https://ncmh.gov.ph/','https://quezoncity.gov.ph/national-suicide-prevention-week-4/',true,true,'2026-09-12T00:00:00Z',4
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='NCMH mobile (Globe/TM)' and phone_number='+639663514518');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','In Touch Community Services','In Touch Crisis Line','+63288937603','24/7 confidential emotional support.','https://in-touch.org/','https://in-touch.org/',true,true,'2026-09-12T00:00:00Z',5
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='In Touch Crisis Line' and phone_number='+63288937603');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','In Touch Community Services','In Touch mobile (Smart)','+639190560709','24/7 confidential emotional support.','https://in-touch.org/','https://in-touch.org/',true,true,'2026-09-12T00:00:00Z',6
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='In Touch mobile (Smart)' and phone_number='+639190560709');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','In Touch Community Services','In Touch mobile (Globe)','+639178001123','24/7 confidential emotional support.','https://in-touch.org/','https://in-touch.org/',true,true,'2026-09-12T00:00:00Z',7
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='In Touch mobile (Globe)' and phone_number='+639178001123');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','In Touch Community Services','In Touch alternate mobile','+639171085412','24/7 confidential emotional support.','https://in-touch.org/','https://in-touch.org/',true,true,'2026-09-12T00:00:00Z',8
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='In Touch alternate mobile' and phone_number='+639171085412');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','Hopeline Philippines','Hopeline PH','+63288044673','Crisis support; current operating hours not independently confirmed.','https://quezoncity.gov.ph/national-suicide-prevention-week-4/','https://quezoncity.gov.ph/national-suicide-prevention-week-4/',true,true,'2026-09-12T00:00:00Z',9
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='Hopeline PH' and phone_number='+63288044673');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','Hopeline Philippines','Hopeline mobile (Globe)','+639175584673','Crisis support; current operating hours not independently confirmed.','https://quezoncity.gov.ph/national-suicide-prevention-week-4/','https://quezoncity.gov.ph/national-suicide-prevention-week-4/',true,true,'2026-09-12T00:00:00Z',10
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='Hopeline mobile (Globe)' and phone_number='+639175584673');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','crisis_hotline','Hopeline Philippines','Hopeline mobile (Smart)','+639188734673','Crisis support; current operating hours not independently confirmed.','https://quezoncity.gov.ph/national-suicide-prevention-week-4/','https://quezoncity.gov.ph/national-suicide-prevention-week-4/',true,true,'2026-09-12T00:00:00Z',11
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='Hopeline mobile (Smart)' and phone_number='+639188734673');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','clinic','Cavite Center for Mental Health','Cavite outpatient department','+63464190013','Contact the clinic for appointment availability; not a confirmed 24/7 crisis line.','https://cavite.gov.ph/directory/','https://cavite.gov.ph/directory/',true,true,'2026-09-12T00:00:00Z',20
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='Cavite outpatient department' and phone_number='+63464190013');
insert into grounding_service.support_resources(country_code,support_resource_type,organization_name,resource_name,phone_number,availability_text,website_url,verification_source,is_active,is_verified,last_verified_at,display_priority)
select 'PH','emergency','Philippine Red Cross','Red Cross emergency hotline','143','Emergency assistance; not a dedicated mental health crisis line.','https://redcross.org.ph/contact-us/','https://redcross.org.ph/contact-us/',true,true,'2026-09-12T00:00:00Z',21
where not exists(select 1 from grounding_service.support_resources where country_code='PH' and resource_name='Red Cross emergency hotline' and phone_number='143');
